import '@/assets/styles/styles.scss'
import Navbar from '@/components/Navbar/Navbar'
import '@notion-x/style/notion-x.scss'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import { Suspense } from 'react'
import { Providers } from './Providers'

const poppins = Poppins({ weight: ['400', '500', '600', '700'], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.className} text-base bg-white text-neutral-900 dark:bg-neutral-900/95 dark:text-neutral-200`}
        suppressHydrationWarning
      >
        <Providers attribute="class" defaultTheme="light" enableColorScheme={false}>
          <Suspense fallback={null}>
            <Navbar />
          </Suspense>
          {/* <BgGlassmorphism /> */}
          {children}
        </Providers>
      </body>
    </html>
  )
}
